### ISSUE TITLE
openapi-gen should fail if `listType=set` is applied to non-scalar

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kube-openapi#323] opened 2022-10-13 17:07 UTC
Today, you can totally do:
```golang
// +listType=set
MyType []SomeStruct
```

which shouldn't be accepted. We should fail with this as early as possible.

**Comment by Jefftree** [comment] 2023-02-17 17:59
Duplicate of https://github.com/kubernetes/kube-openapi/issues/343
/close

**Closed by Jefftree** 2023-02-17 17:59 UTC
Labels: lifecycle/frozen
